[language-server.diagnostic-ls]
command = "diagnostic-languageserver"
args = ["--stdio"]

[language-server.diagnostic-ls.config.linters.cspell]
sourceName = "cspell"
command = "cspell"
args = [
  "--config",
  ".cspell.yaml",
  "lint",
  "stdin://%filepath",
  "--no-progress",
  "--no-summary",
]
rootPatterns = [".cspell.yaml"]
formatPattern = [".*:(\\d+):(\\d+) - (.*)", { line = 1, column = 2, message = 3 }]

[language-server.diagnostic-ls.config.filetypes]
markdown = "cspell"

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "go-template"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true
language-servers = ["diagnostic-ls"]

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true
